locks: 
- name: "deadman_stop"
  topic: "/deadman_stop"
  timeout: 1.0 # After msg stops sending, keep lock for this amount of time
  priority: 5

topics:
- name    : bt_joy
  topic   : bluetooth_teleop/cmd_vel
  timeout : 0.5
  priority: 9
- name    : interactive_marker
  topic   : twist_marker_server/cmd_vel
  timeout : 0.5
  priority: 8
- name    : external
  topic   : cmd_vel
  timeout : 0.5
  priority: 1
